---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "GDAL SRS Barn Raising"
keywords:    "SRS, WKT2, Coordinate Systems, SQLite"
description: "An fundraising effort to improve the coordinate system handling of PROJ, libgeotiff, and GDAL"
source_link: "https://github.com/hobu/gdalbarn"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#afd3ed'
  green:     '#c0d88c'
  purple:    '#c869bf'
  orange:    '#fcd283'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

